import {
  FileText,
  GithubIcon as Github,
  GitlabIcon as Gitlab,
  SlackIcon as Slack,
  TrelloIcon as Trello,
  CalendarIcon as Calendar,
} from 'lucide-react';

export const AVAILABLE_INTEGRATIONS = {
  notion: {
    id: 'notion',
    name: 'Notion',
    description: 'Import pages and databases from Notion.',
    icon: FileText,
    popular: true,
    featured: true,
    available: true,
    category: 'productivity',
  },
  github: {
    id: 'github',
    name: 'GitHub',
    description: 'Link GitHub issues and pull requests to your tasks.',
    icon: Github,
    popular: true,
    available: false,
    category: 'development',
  },
  slack: {
    id: 'slack',
    name: 'Slack',
    description: 'Send notifications and updates to your Slack channels.',
    icon: Slack,
    popular: true,
    available: false,
    category: 'communication',
  },
  gitlab: {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Link GitLab issues and merge requests to your tasks.',
    icon: Gitlab,
    popular: false,
    available: false,
    category: 'development',
  },
  'google-calendar': {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Sync your tasks with Google Calendar.',
    icon: Calendar,
    popular: false,
    available: false,
    category: 'productivity',
  },
  trello: {
    id: 'trello',
    name: 'Trello',
    description: 'Import boards and cards from Trello.',
    icon: Trello,
    popular: false,
    available: false,
    category: 'productivity',
  },
};
